version: "3.8"

services:
  mariadb:
    image: mariadb/columnstore
    container_name: mcs_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - columnstore_data:/var/lib/columnstore
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - analytics-net

  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    networks:
      - analytics-net

volumes:
  columnstore_data:
  mariadb_data:

networks:
  analytics-net:
