services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    network_mode: "host"
    environment:
      - DB_HOST=127.0.0.1
      - MLFLOW_TRACKING_URI=http://127.0.0.1:5000
    volumes:
      - ./saved_models:/app/saved_models
      - ./configs:/app/configs

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    network_mode: "host"
    environment:
      - BACKEND_URL=http://127.0.0.1:8000
      - NEXT_PUBLIC_MLFLOW_URL=http://127.0.0.1:5000

