ingestion:
  source_directory: "./Raw_Data/"
  batch_size: 500000
  files:
    - name: "train"
      path: "./Raw_Data/train.csv"
      table: "fact_energy_usage"
    - name: "building"
      path: "./Raw_Data/building_metadata.csv"
      table: "dim_building"
    - name: "weather"
      path: "./Raw_Data/weather_train.csv"
      table: "dim_weather"
  test:
    - name: "test"
      path: "./Raw_Data/test.csv"
    - name: "building"
      path: "./Raw_Data/building_metadata.csv"
    - name: "weather"
      path: "./Raw_Data/weather_test.csv"
db:
  dialect: "mysql+pymysql"
  host: "localhost"
  docker_host: "mcs_container"
  port: 3306
  database: "ashrae_db"
  user: "student"
  password: "Student%40123%21"
redis:
  host: "127.0.0.1"
  port: 6379
mlflow:
  tracking_uri: "http://localhost:5000"
  experiment_name: "ASHRAE_Energy_Prediction"
  model_name: "LGBM_Energy_Model"
training:
  model_save_path: "saved_models/model.pkl"
  sample_size: 500000
  use_sample: True
monitoring:
  reference_data_path: "saved_models/reference_data.parquet"
  sample_size: 500
